<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto

namespace Booking;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>booking.CreateBookingRequest</code>
 */
class CreateBookingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 room_id = 1;</code>
     */
    protected $room_id = 0;
    /**
     * Generated from protobuf field <code>string customer_name = 2;</code>
     */
    protected $customer_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $room_id
     *     @type string $customer_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Booking::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 room_id = 1;</code>
     * @return int
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>int32 room_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkInt32($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_name = 2;</code>
     * @return string
     */
    public function getCustomerName()
    {
        return $this->customer_name;
    }

    /**
     * Generated from protobuf field <code>string customer_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_name = $var;

        return $this;
    }

}

