<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto

namespace GPBMetadata;

class Booking
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE3\x02\x0A\x0Dbooking.proto\x12\x07booking\"\x1C\x0A\x0EBookingRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\">\x0A\x14CreateBookingRequest\x12\x0F\x0A\x07room_id\x18\x01 \x01(\x05\x12\x15\x0A\x0Dcustomer_name\x18\x02 \x01(\x09\"E\x0A\x0FBookingResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x0F\x0A\x07room_id\x18\x02 \x01(\x05\x12\x15\x0A\x0Dcustomer_name\x18\x03 \x01(\x092\x9B\x01\x0A\x0EBookingService\x12?\x0A\x0AGetBooking\x12\x17.booking.BookingRequest\x1A\x18.booking.BookingResponse\x12H\x0A\x0DCreateBooking\x12\x1D.booking.CreateBookingRequest\x1A\x18.booking.BookingResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

