<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoomService.proto

namespace Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>room.RoomListResponse</code>
 */
class RoomListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .room.RoomResponse rooms = 1;</code>
     */
    private $rooms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Room\RoomResponse[] $rooms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoomService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .room.RoomResponse rooms = 1;</code>
     * @return RepeatedField<\Room\RoomResponse>
     */
    public function getRooms()
    {
        return $this->rooms;
    }

    /**
     * Generated from protobuf field <code>repeated .room.RoomResponse rooms = 1;</code>
     * @param \Room\RoomResponse[] $var
     * @return $this
     */
    public function setRooms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Room\RoomResponse::class);
        $this->rooms = $arr;

        return $this;
    }

}

