<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoomService.proto

namespace Room;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>room.RoomResponse</code>
 */
class RoomResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string price = 4;</code>
     */
    protected $price = '';
    /**
     * Generated from protobuf field <code>string wifi = 5;</code>
     */
    protected $wifi = '';
    /**
     * Generated from protobuf field <code>string room_type = 6;</code>
     */
    protected $room_type = '';
    /**
     * Generated from protobuf field <code>string image = 7;</code>
     */
    protected $image = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $title
     *     @type string $description
     *     @type string $price
     *     @type string $wifi
     *     @type string $room_type
     *     @type string $image
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoomService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string price = 4;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>string price = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wifi = 5;</code>
     * @return string
     */
    public function getWifi()
    {
        return $this->wifi;
    }

    /**
     * Generated from protobuf field <code>string wifi = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setWifi($var)
    {
        GPBUtil::checkString($var, True);
        $this->wifi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_type = 6;</code>
     * @return string
     */
    public function getRoomType()
    {
        return $this->room_type;
    }

    /**
     * Generated from protobuf field <code>string room_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomType($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image = 7;</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>string image = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

}

