<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoomService.proto

namespace GPBMetadata;

class RoomService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF2\x02\x0A\x11RoomService.proto\x12\x04room\"\x19\x0A\x0BRoomRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\"}\x0A\x0CRoomResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x0D\x0A\x05title\x18\x02 \x01(\x09\x12\x13\x0A\x0Bdescription\x18\x03 \x01(\x09\x12\x0D\x0A\x05price\x18\x04 \x01(\x09\x12\x0C\x0A\x04wifi\x18\x05 \x01(\x09\x12\x11\x0A\x09room_type\x18\x06 \x01(\x09\x12\x0D\x0A\x05image\x18\x07 \x01(\x09\"5\x0A\x10RoomListResponse\x12!\x0A\x05rooms\x18\x01 \x03(\x0B2\x12.room.RoomResponse\"\x09\x0A\x07PBEmpty2s\x0A\x0BRoomService\x120\x0A\x07GetRoom\x12\x11.room.RoomRequest\x1A\x12.room.RoomResponse\x122\x0A\x09ListRooms\x12\x0D.room.PBEmpty\x1A\x16.room.RoomListResponseb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

